import type { Review } from "@/components/ReviewCard";

export type SiteReview = Review & {
  id: string;
  service: string;
  borough: string;
  date: string;
};

export const reviewServices = [
  "All",
  "House Removals",
  "Man & Van",
  "Sofa Delivery",
  "Office Removals",
  "Packing",
] as const;

export const siteReviews: SiteReview[] = [
  {
    id: "sarah-noah",
    name: "Sarah Noah",
    location: "Islington, London",
    borough: "Islington",
    service: "House Removals",
    rating: 5,
    date: "2026-06-12",
    text: "The crew arrived on time, wrapped everything with care and had us fully moved in before lunch. Fixed price with no surprises — the most stress-free move we've ever had.",
    avatar: "/reviews/sarah-noah.jpg",
  },
  {
    id: "jamie-carter",
    name: "Jamie Carter",
    location: "Hackney, London",
    borough: "Hackney",
    service: "Man & Van",
    rating: 5,
    date: "2026-05-28",
    text: "Booked a last-minute man & van and they still turned up early. Polite, quick and genuinely careful with every single box. Couldn't recommend them more.",
    avatar: "/reviews/jamie-carter.jpg",
  },
  {
    id: "marie-roberts",
    name: "Marie Roberts",
    location: "Croydon, London",
    borough: "Croydon",
    service: "House Removals",
    rating: 5,
    date: "2026-05-10",
    text: "From the free survey to the final box, everything was smooth. The fixed quote didn't change by a single penny and the team was lovely throughout.",
    avatar: "/reviews/marie-roberts.jpg",
  },
  {
    id: "alena-carty",
    name: "Alena Carty",
    location: "Camden, London",
    borough: "Camden",
    service: "House Removals",
    rating: 5,
    date: "2026-04-22",
    text: "The crew wrapped every piece of furniture and had us moved across town before lunch. Fixed price with no surprises — the most stress-free move we've ever had.",
    avatar: "/reviews/alena-carty.jpg",
  },
  {
    id: "mark-taylor",
    name: "Mark Taylor",
    location: "Greenwich, London",
    borough: "Greenwich",
    service: "Sofa Delivery",
    rating: 5,
    date: "2026-04-08",
    text: "Polite, quick and genuinely careful with every single box. They got a huge sofa up a narrow staircase without a scratch. Couldn't recommend them more.",
    avatar: "/reviews/mark-taylor.jpg",
  },
  {
    id: "emelia-grace",
    name: "Emelia Grace",
    location: "Wandsworth, London",
    borough: "Wandsworth",
    service: "Packing",
    rating: 5,
    date: "2026-03-30",
    text: "We added full packing and it was worth every penny. Kitchen glassware arrived perfect and the crew labelled every box clearly for unpacking.",
    avatar: "/reviews/emelia-grace.jpg",
  },
  {
    id: "ben-shawatz",
    name: "Ben Shawatz",
    location: "Westminster, London",
    borough: "Westminster",
    service: "Office Removals",
    rating: 5,
    date: "2026-03-14",
    text: "Weekend office move finished before Monday open. Clear plan, careful with monitors and desks, and the fixed quote held end to end.",
    avatar: "/reviews/ben-shawatz.jpg",
  },
  {
    id: "eli-chen",
    name: "Eli Chen",
    location: "Tower Hamlets, London",
    borough: "Tower Hamlets",
    service: "Man & Van",
    rating: 4,
    date: "2026-02-26",
    text: "Great for a same-day flat clear-out. One extra flight of stairs took a little longer, but the team stayed cheerful and careful throughout.",
    avatar: "/reviews/eli-chen.jpg",
  },
  {
    id: "oliva-smith",
    name: "Oliva Smith",
    location: "Barnet, London",
    borough: "Barnet",
    service: "House Removals",
    rating: 5,
    date: "2026-02-11",
    text: "Family house move with kids in tow — the crew were patient, protected floors and doors, and had us settled by mid-afternoon.",
    avatar: "/reviews/oliva-smith.jpg",
  },
  {
    id: "abhinav-arora",
    name: "Abhinav Arora",
    location: "Ealing, London",
    borough: "Ealing",
    service: "Sofa Delivery",
    rating: 5,
    date: "2026-01-29",
    text: "Marketplace sofa collection and delivery in one trip. On time, careful with the walls, and priced exactly as quoted on WhatsApp.",
    avatar: "/reviews/abhinav-arora.jpg",
  },
];
